Web/Controllers/CtoVController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Web.Models;
using Web.Models.ViewModels;

namespace Web.Controllers
{
    public class CtoVController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();
        // GET: CtoV
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 使用 ViewData 傳遞資料
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoViewData()
        {
            //Key:          Name
            //Data(Value):  Downey
            ViewData["Name"] = "Downey";
            return View();
        }

        /// <summary>
        /// 使用 ViewBag 傳遞資料
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoViewBag()
        {
            ViewBag.Name = "Downey";
            return View();
        }

        /// <summary>
        /// 使用 ViewData 傳遞 List 型態的資料
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoVDModel()
        {
            ViewData["products"] = db.Products.ToList();
            return View();
        }

        /// <summary>
        /// 使用 ViewData.Model(ViewModel) 傳遞 List 型態的資料
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoStronglytyped()
        {
            return View(db.Products.ToList());
        }

        #region 測試使用 TempData 傳遞資料
        public ActionResult DemoInput()
        {
            return View();
        }

        public ActionResult CheckInput(string Name)
        {
            if (string.IsNullOrEmpty(Name))
            {
                TempData["Error"] = "輸入不得空白";
                return RedirectToAction("DemoInput");
            }
            ViewBag.name = Name;
            return View();
        }
        #endregion

        #region 測試使用個項傳遞物件傳遞資料，在單一 Requse 中會有什麼情況(可搭配中斷點觀察)
        public ActionResult DemoTempDate()
        {
            ViewData["Msg1"] = "VD 資料(ViewDate)";
            ViewBag.Msg2 = "VB 資料(ViewBag)";
            TempData["Msg3"] = "TD 資料(TempDate)";
            return RedirectToAction("Redirect1");
        }

        public ActionResult Redirect1()
        {
            //處理資料
            TempData["Msg4"] = TempData["Msg3"];
            return RedirectToAction("GetRedirectData");
        }

        public ActionResult GetRedirectData()
        {
            return View();
        }
        #endregion

        #region 測試 TempData 傳遞資料(多 Requse)
        public ActionResult DemoTempdataProduct()
        {
            TempData["Products"] = db.Products.ToList();
            return Redirect("DemoTempDataKeep");
        }

        public ActionResult DemoTempDataKeep()
        {            
            return View();
        }
        #endregion

        #region 多 Model 物件傳遞
        public ActionResult DemoInclude()
        {
            var products = db.Products
                .Include(x => x.Category)
                .Include(x => x.Supplier);
            return View();
        }
        #endregion

        #region SelectList 物件傳遞
        public ActionResult DemoSelectList()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            ViewBag.SupplierID = new SelectList(db.Suppliers, "SupplierID", "CompanyName");
            return View();
        }
        #endregion

        #region 多類別(物件)傳遞；比較麻煩的範例
        public ActionResult DemoMultiModelObject()
        {
            ViewBag.Author = "Downey";
            ViewBag.Book = "Book Name書名";
            ViewBag.Product = (from p in db.Products select p).Take(10).ToList();
            ViewBag.Category = (from c in db.Categories select c).Take(10).ToList();
            return View();
        }
        #endregion

        #region 多類別(物件)傳遞；較好的方式
        public ActionResult DemoViewModel()
        {
            return View(new ProductCategoryViewModel() {
                Name = "Downey",
                Book = "Book Name書名",
                Product = (from p in db.Products select p).Take(10).ToList(),
                Category = (from c in db.Categories select c).Take(10).ToList()
            });
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Views/CtoV/CheckInput.cshtml
@{
    ViewBag.Title = "CheckInput";
}

<h2>CheckInput</h2>

<p>Name:@ViewBag.name</p>

Web/Views/CtoV/DemoInclude.cshtml
@model IEnumerable<Web.Models.Product>
@{
    ViewBag.Title = "DemoInclude";
}

<h2>DemoInclude</h2>

<table>
    <tr>
        <th>@Html.DisplayNameFor(x => x.Category.CategoryName)</th>
        <th>@Html.DisplayNameFor(x => x.Supplier.CompanyName)</th>
    </tr>
    @foreach(var item in Model)
    {
    <tr>
        <td>@Html.DisplayFor(x => item.ProductName)</td>
        <td>@Html.DisplayFor(x => item.Category.CategoryName)</td>
        <td>@Html.DisplayFor(x => item.Supplier.CompanyName)</td>
    </tr>
    }
</table>

Web/Views/CtoV/DemoInput.cshtml
@{
    ViewBag.Title = "DemoInput";
}

<h2>DemoInput</h2>
<div>
    @using (Html.BeginForm("CheckInput", "CtoV"))
    {
        <input type="text" name="Name" />
        <br />
        <span style="color:red">@TempData["Error"]</span>
        <br />
        <input type="submit" value="送出" />
    }
</div>

Web/Views/CtoV/DemoMultiModelObject.cshtml
<h2>DemoMultiModelObject</h2>
<div>
    <ul>
        <li>@ViewBag.Author</li>
        <li>@ViewBag.Book</li>
    </ul>
</div>

<h3>Product Name</h3>
<ul>
    @foreach (var item in ViewBag.Product as List<Product>)
    {
        <li>@item.ProductName</li>
    }
</ul>

<h3>Category Name</h3>
<ul>
    @foreach (var item in ViewBag.Category as List<Category>)
    {
        <li>@item.CategoryName</li>
    }
</ul>

Web/Views/CtoV/DemoSelectList.cshtml
@model Web.Models.Product

@{
    ViewBag.Title = "DemoSelectList";
}

<h2>DemoSelectList</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupplierID, "SupplierID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupplierID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupplierID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantityPerUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantityPerUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantityPerUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsInStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsInStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsOnOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsOnOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsOnOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReorderLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReorderLevel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReorderLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discontinued, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Discontinued)
                    @Html.ValidationMessageFor(model => model.Discontinued, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Web/Views/CtoV/DemoStronglytyped.cshtml
@model IEnumerable<Product>
@{
    ViewBag.Title = "DemoStronglytyped";
}

<h2>DemoStronglytyped</h2>

<ul>
    @foreach(var item in Model)
    {
        <li>@item.ProductName</li>
    }
</ul>

Web/Views/CtoV/DemoTempDataKeep.cshtml
@{
    ViewBag.Title = "DemoTempDataKeep";
    var products = TempData["Products"] as List<Product>;
    TempData.Keep();
}

<h2>DemoTempDataKeep</h2>
<ul>
    @foreach(var item in products)
    {
        <li >@item.ProductName</li>
    }
</ul>

Web/Views/CtoV/DemoVDModel.cshtml
@{
    ViewBag.Title = "DemoVDModel";
}

<h2>DemoVDModel</h2>
<ul>
    @foreach (var item in ViewData["products"] as List<Product>)
    {
        <li>@item.ProductName</li>
    }
</ul>

Web/Views/CtoV/DemoViewBag.cshtml
@{
    ViewBag.Title = "DemoViewBag";
}

<h2>DemoViewBag</h2>
Name: @ViewBag.Name

Web/Views/CtoV/DemoViewData.cshtml
@{
    ViewBag.Title = "DemoViewData";
}

<h2>DemoViewData</h2>
Name: @ViewData["Name"]

Web/Views/CtoV/DemoViewModel.cshtml
@model Web.Models.ViewModels.ProductCategoryViewModel

@{
    ViewBag.Title = "DemoViewModel";
}

<h2>DemoViewModel</h2>

<div>
    <ul>
        <li>@Model.Name</li>
        <li>@Model.Book</li>
    </ul>
</div>

<h3>Product Name</h3>
<ul>
    @foreach (var item in Model.Product)
    {
        <li>@item.ProductName</li>
    }
</ul>

<h3>Category Name</h3>
<ul>
    @foreach (var item in Model.Category)
    {
        <li>@item.CategoryName</li>
    }
</ul>

Web/Views/CtoV/GetRedirectData.cshtml
@{
    ViewBag.Title = "GetRedirectData";
}

<h2>GetRedirectData</h2>
<ul>
    <li>ViewData-Msg1:@ViewData["Msg1"]</li>
    <li>ViewBag -Msg2:@ViewBag.Msg2</li>
    <li>TempData-Msg3:@TempData["Msg3"]</li>
    <li>TempData-Msg4:@TempData["Msg4"]</li>
</ul>

Web/Views/CtoV/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div>
    <ul>
        <li><a href="/CtoV/DemoViewData">DemoViewData</a></li>
        <li><a href="/CtoV/DemoViewBag">DemoViewBag</a></li>
        <li><a href="/CtoV/DemoVDModel">DemoVDModel</a></li>
        <li><a href="/CtoV/DemoInput">DemoInput</a></li>
        <li><a href="/CtoV/DemoStronglytyped">DemoStronglytyped</a></li>
        <li><a href="/CtoV/DemoTempDate">DemoTempDate</a></li>
        <li><a href="/CtoV/DemoTempdataProduct">DemoTempdataProduct</a></li>
        <li><a href="/CtoV/DemoSelectList">DemoSelectList</a></li>
        <li><a href="/CtoV/DemoMultiModelObject">DemoMultiModelObject</a></li>
        <li><a href="/CtoV/DemoViewModel">DemoViewModel</a></li>
    </ul>
</div>