Web/Controllers/MvcTypeController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Web.Models;
using Web.Models.ViewModels;
using Web.Extensions;

namespace Web.Controllers
{
    public class MvcTypeController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();

        // GET: MvcType
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Demo Content Result(不指定內容類型)
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoContent()
        {
            return Content("Test Content by no type.");
        }

        /// <summary>
        /// Demo Content Result(指定內容為 Html 類型)
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoHtmlContent()
        {
            return Content("<h1>Test Html Content</h1><p>測試 Html 類型內容</p>", "text/html");
        }

        /// <summary>
        /// Demo Content Result(指定以 UTF-8 編碼之 html 類型內容)
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoEncodingContent()
        {
            return Content("<h1>Test html content encoding by UTF-8.</h1><p>測試以 UTF-8 編碼之 html 內容</p><p>テストコンテンツ</p>", "text/html", Encoding.UTF8);
        }

        /// <summary>
        /// Demo Content Result(指定內容為 csv 類型)
        /// 要求此 ActionResult 時瀏覽器會提示是否下載檔案
        /// 下載的檔案附檔名改為 .csv 就可以用 Excel 開啟
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoCsvContent()
        {
            return Content("Name,Age\r\nDowney,24\r\n", "text/csv");
        }

        /// <summary>
        /// Demo Content Result(指定內容為 XML 類型)
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoXmlContent()
        {
            string XmlString = "<root><name>Downey Chang</name></root>";
            return Content(XmlString, "text/xml", Encoding.UTF8);
        }

        /// <summary>
        /// Demo ActionResult 轉型失敗預設以 ContentResult 進行處理
        /// 傳回內容須能被 Convert.ToString() 轉換
        /// </summary>
        /// <returns></returns>
        public int ProductsCount()
        {
            return db.Products.Count();
        }

        #region Demo 需要由 Server 設置的 JS
        /// <summary>
        /// 實體頁面
        /// </summary>
        /// <returns></returns>
        public ActionResult OnlineGame()
        {
            return View();
        }

        /// <summary>
        /// 被要求的 JS 設置方
        /// </summary>
        /// <returns></returns>
        public ActionResult NextTime()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendFormat("var nextTime = '{0}';\r\n", DateTime.UtcNow);
            return JavaScript(sb.ToString());
        }
        #endregion

        #region Demo 使用 Json 格式傳遞資料
        /// <summary>
        /// 傳遞指定類型物件
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoJson1()
        {
            Models.ViewModels.Person person = new Models.ViewModels.Person()
            {
                Name = "Downey",
                Age = 20
            };

            return Json(person, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 傳遞匿名型別類型物件，及測試時間格式
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoJson2()
        {
            var person = new
            {
                Name = "Downey",
                Age = 20,
                Birthday = new DateTime(2099,9,9)
            };
            return Json(person, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Demo 使用 Json 傳遞 Entity 物件
        /// 順便 Demo HttpStatusCode
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DemoJsonModel(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.Configuration.LazyLoadingEnabled = false;
            Product product = db.Products.Find(id);
            return Json(product);
        }

        /// <summary>
        /// Demo 以 Json 傳到物件到 Controller 是否能正常 Model Binding
        /// </summary>
        /// <param name="p"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetPersonJson(Models.Person[] p)
        {
            return Json(p, JsonRequestBehavior.AllowGet);
        }
        #endregion

        /// <summary>
        /// Demo Redirect 重新導向功能類別
        /// </summary>
        /// <param name="param"></param>
        /// <returns></returns>
        public ActionResult DemoRedirect(string param)
        {
            if (!string.IsNullOrEmpty(param))
            {
                string baseUrl = "https://ithelp.ithome.com.tw/announces/";//重新導向網址(這裡導向 IT 鐵人邦的公告xD)
                Uri url = new Uri(baseUrl + param);
                return Redirect(url.ToString()); // 302
                //return RedirectPermanent(url.ToString()); // 301
            }
            else
            {
                return Content("error");
            }
        }

        /// <summary>
        /// Demo 以實體檔案路徑作為來源的 File Result
        /// File Result 類別代表一個可下載的檔案
        /// </summary>
        /// <returns></returns>
        public ActionResult DemoFilePath()
        {
            string path = Server.MapPath(@"~/Content/Site.css");
            return File(path, "text/css");
        }

        #region Demo Upload File
        //上傳需確認伺服器端有此路徑(程式不會自己建立資料夾)
        public ActionResult UploadToDisk()
        {
            ViewBag.Title = "UploadToDisk";
            return View("UploadFile");
        }

        [HttpPost]
        public ActionResult UploadToDisk(IEnumerable<HttpPostedFileBase> file)
        {
            string message = string.Empty;
            if (file.Count() > 0)
            {
                int i = 0;
                foreach (var F in file)
                {
                    message +=  $"<h3>檔案{i}：</h3>";
                    if (F == null)
                    {
                        message += "沒有選到檔案。";
                    }
                    else
                    {
                        if (F.ContentLength > 0)
                        {
                            string FileName = Path.GetFileName(F.FileName);
                            string UploadPath = Path.Combine(Server.MapPath("~/File/"), FileName);
                            F.SaveAs(UploadPath);
                            message += $" 檔案名稱：{FileName}<br /> 上傳檔案類型(MIME)：{F.ContentType}<br /> 檔案大小：{F.ContentLength} Byte<br /> 上傳成功！<hr />";
                        }
                        else
                        {
                            message += "請勿上傳空白檔案。";
                        }
                    }
                    i += 1;
                }
                TempData["Message"] = message;
            }
            else
            {
                TempData["Message"] = "你好像很不會上傳檔案喔？";
            }
            return View("UploadFile");
            //return RedirectToAction("UploadToDisk");
        }

        //上傳到 DB
        public ActionResult UploadToDb()
        {
            ViewBag.Title = "UploadToDb";
            return View("UploadFile");
        }

        [HttpPost]
        public ActionResult UploadToDb(IEnumerable<HttpPostedFileBase> file)
        {
            string message = string.Empty;
            if (file.Count() > 0)
            {
                //保證資料一致性，將所有資料 Add 完以後，再呼叫 db.SaveChanges() 方法
                //若有上傳失敗的檔案則不會叫到此方法
                try
                {
                    int i = 0;
                    foreach (var F in file)
                    {
                        message += $"<h3>檔案{i}：</h3>";
                        if (F == null)
                        {
                            message += "沒有選到檔案。";
                        }
                        else
                        {
                            if (F.ContentLength > 0)
                            {
                                string FileName = Path.GetFileName(F.FileName);
                                int FileLength = F.ContentLength;
                                byte[] buffer = new byte[FileLength];
                                //讀取 Stream，寫入 Buffer
                                F.InputStream.Read(buffer, 0, FileLength);
                                DbFile dbFile = new DbFile()
                                {
                                    Name = FileName,
                                    MimeType = F.ContentType,
                                    Size = FileLength,
                                    Content = buffer
                                };
                                DbFile NewRow = db.DbFiles.Add(dbFile);

                                message += $" 檔案ID：{NewRow.Id}<br /> 檔案名稱：{FileName}<br /> 上傳檔案類型(MIME)：{F.ContentType}<br /> 檔案大小：{FileLength} Byte<br /> 上傳成功！<hr />";
                            }
                            else
                            {
                                message += "請勿上傳空白檔案。";
                            }
                        }
                        i += 1;
                    }
                    db.SaveChanges();
                }
                catch(Exception ex)
                {
                    message = $"檔案上傳失敗，錯誤訊息：<br />{ex.Message}";
                }
            }
            else
            {
                message = "你好像很不會上傳檔案喔？";
            }
            TempData["Message"] = message;
            return View("UploadFile");
        }
        #endregion

        #region Get File
        /// <summary>
        /// 下載檔案頁面
        /// </summary>
        /// <returns></returns>

Web/Views/MvcType/Api1.cshtml
@{
    ViewBag.Title = "Api1";
}

<h2>Api1</h2>

@section Scripts {
    <script type="text/javascript">
        var jsonStr = "";
    </script>
}

Web/Views/MvcType/DemoActionName.cshtml
@{
    ViewBag.Title = "DemoActionName";
}

<h2>DemoActionName</h2>
<div>
    @ViewBag.ViewName@ViewBag.Title
</div>

Web/Views/MvcType/DemoActionName2.cshtml
@{
    ViewBag.Title = "DemoActionName2";
}

<h2>DemoActionName2</h2>
<div>
    @ViewBag.ViewName@ViewBag.Title
</div>

Web/Views/MvcType/DemoFileContent.cshtml
@model List<SelectListItem>
@{
    ViewBag.Title = "DemoFileContent";
}

<h2>DemoFileContent</h2>
<div>
    <span>@Html.Raw(TempData["Message"])</span>
    
    @using (Html.BeginForm("DemoFileContent", "MvcType", FormMethod.Post))
    {
        <div>
            @*<select name="id">

                @foreach (var F in ViewBag.AllFile)
                {
                    <option value="@F.Id">@F.Name</option>
                }
            </select>
            *@
            @Html.DropDownList("FileId", Model)
        </div>
        <hr />
        <input type="submit" name="name" value="下載" />
    }

</div>

Web/Views/MvcType/DemoMaster.cshtml
@{
    ViewBag.Title = "DemoMaster";
}

<h2>DemoMaster</h2>

Web/Views/MvcType/DemoPartialView.cshtml
@{
    ViewBag.Title = "DemoPartialView";
}

<h2>DemoPartialView</h2>
<p>請稍等約3秒鐘...</p>
<div id="now">

</div>
@section Scripts{
    <script type="text/javascript">
        $(function () {
            $.get(
                "@Url.Action("GetTime")",
                null,
                function (res) {
                    $('#now').html(res);
                }                
            );
        });
    </script>
}

Web/Views/MvcType/Index.cshtml
@{
    ViewBag.Title = "MvcType";
}
<h1>MvcType</h1>
<h2>Index</h2>
<div>
    <ul>
        <li><a href="@Url.Action("DemoContent","MvcType")">DemoContent</a></li>
        <li><a href="@Url.Action("DemoHtmlContent","MvcType")">DemoHtmlContent</a></li>
        <li><a href="@Url.Action("DemoEncodingContent","MvcType")">DemoEncodingContent</a></li>
        <li><a href="@Url.Action("DemoCsvContent","MvcType")">DemoCsvContent</a></li>
        <li><a href="@Url.Action("DemoXmlContent","MvcType")">DemoXmlContent</a></li>
        <li><a href="@Url.Action("ProductsCount","MvcType")">ProductsCount</a></li>
        <li><a href="@Url.Action("OnlineGame","MvcType")">OnlineGame</a></li>
        <li><a href="@Url.Action("DemoFilePath","MvcType")">DemoFilePath</a></li>
        <li><a href="@Url.Action("UploadToDisk","MvcType")">UploadToDisk</a></li>
        <li><a href="@Url.Action("UploadToDb","MvcType")">UploadToDb</a></li>
        <li><a href="@Url.Action("DemoFileContent","MvcType")">DemoFileContent</a></li>
        <li><a href="@Url.Action("GetDeskFile","MvcType")?FileName=A.jpg">Download File(A.jpg)</a></li>
        <li><a href="@Url.Action("ShowImage","MvcType")">ShowImage</a></li>
        <li><a href="@Url.Action("DemoFileStream","MvcType")?FileName=A.jpg">DemoFileStream(A.jpg)</a></li>
        <li><a href="@Url.Action("TestApi","MvcType")">TestApi</a></li>
        <li><a href="@Url.Action("DemoActionName","MvcType")">DemoActionName</a></li>
        <li><a href="@Url.Action("DemoMaster","MvcType")">DemoMaster</a></li>
        <li><a href="@Url.Action("DemoPartialView","MvcType")">DemoPartialView</a></li>
        <li><a href="@Url.Action("DemoVideo","MvcType")">DemoVideo</a></li>
        <li><a href="@Url.Action("ShowVideo","MvcType")">ShowVideo</a></li>
        <li><a href="@Url.Action("Secure","MvcType")">Secure</a></li>
    </ul>
</div>

Web/Views/MvcType/OnlineGame.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OnlineGame</title>
    <script src="@Url.Action("NextTime", "MvcType")"></script>
</head>
<body>
    <div> 
        <script type="text/javascript">
            alert('伺服器時間：' + nextTime);
        </script>
    </div>
</body>
</html>

Web/Views/MvcType/Secure.cshtml
@{
    ViewBag.Title = "Secure";
}

<h2>Secure</h2>
<p>請注意網址</p>

Web/Views/MvcType/ShowImage.cshtml
@model List<SelectListItem>
@{
    ViewBag.Title = "ShowImage";
}

<h2>ShowImage</h2>
<div>
    @Html.DropDownList("ImageName", Model)
</div>
<img id="Img1" alt="沒有這張圖片" style="width:50%" />

@section Scripts {
    <script type="text/javascript">
        var actionUrl = "@Url.Action("GetDeskFile")";
        $(function () {
            ChangImg($('#ImageName').val());
            $('#ImageName').change(function () {
                ChangImg($(this).val());
            });
        });

        function ChangImg(fileName) {
            $('#Img1').attr('src', actionUrl + '?FileName=' + fileName);
        };
    </script>
}

Web/Views/MvcType/ShowVideo.cshtml
@{
    ViewBag.Title = "ShowVideo";
}

<h2>ShowVideo</h2>
<div>
    <video controls="controls">
        <source src="@Url.Action("DemoVideo","MvcType")" type="video/mp4" />
    </video>
</div>

Web/Views/MvcType/TestApi.cshtml
@{
    ViewBag.Title = "TestApi";
}

<h2>TestApi</h2>
<div>
    <input type="button" id="AddName" value="新增" />
    <a>    </a>
    <input type="button" id="DelName" value="減少" />
    <form id="NameList">
        <p><input type="text" id="NameList" name="NameList" class="NL" value="" /></p>
    </form>
    <input type="button" id="submitList" value="送出" />
</div>

<hr />
<div class="jsonContent">
    @Html.AntiForgeryToken()
</div>

@section Scripts {
    <script type="text/javascript" >
        $(function () {
            $("#AddName").click(function () {
                var newTag = $("<p>").append(
                    $("<input>").attr("type", "text").attr("id", "NameList" + $('#NameList input').length).attr("name", "NameList").addClass("NL")
                );
                $("#NameList").append(newTag);
            });

            $('#DelName').click(function () {
                if ($('#NameList input').length > 1) {
                    $('#NameList input').last().remove();
                }
            });

            $('#submitList').click(function () {
                $.ajax({
                    url: "@Url.Action("Api1")",
                    data: $('#NameList').serializeArray(),
                    error: function () {
                        alert("Error");
                    },
                    success: function (response) {
                        var newTag = $("<p>").append("Json Response:" + response);
                        $('.jsonContent').append(newTag);
                    }
                });
            });
        });
    </script>
}

Web/Views/MvcType/UploadFile.cshtml
@{    
    string ActionName = ViewBag.Title;
}

<h2>@ActionName</h2>
<div>
    <span>@Html.Raw(TempData["Message"])</span>
    @using (Html.BeginForm(ActionName, "MvcType", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            <input type="button" id="AddFile" value="增加檔案" />
            <label style="width:50px"></label>
            <input type="button" id="DelFile" value="減少檔案" />
        </div>
        <hr />
        <div class="uploadFile">
            <p><input type="file" id="file" name="file" /></p>
        </div>
        <hr />
        <div>
            <input type="submit" value="上傳" />
        </div>
    }
</div>
@section Scripts {
    <script type="text/javascript" src="~/Scripts/MvcType/AddFile.js"></script>
}

Web/Views/MvcType/_GetTimePartial.cshtml
<div>@DateTime.Now.ToString()</div>